# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/gus/floorplanning/floorplanning.cache/wt [current_project]
set_property parent.project_path /home/gus/floorplanning/floorplanning.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_blk_mem_gen_0_0/base_zynq_design_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_bram_ctrl_0_0/base_zynq_design_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_0/base_zynq_design_axi_usb2_device_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_0/base_zynq_design_axi_usb2_device_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_0/base_zynq_design_axi_usb2_device_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_1/base_zynq_design_axi_usb2_device_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_1/base_zynq_design_axi_usb2_device_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_1/base_zynq_design_axi_usb2_device_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_2/base_zynq_design_axi_usb2_device_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_2/base_zynq_design_axi_usb2_device_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_2/base_zynq_design_axi_usb2_device_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_3/base_zynq_design_axi_usb2_device_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_3/base_zynq_design_axi_usb2_device_0_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_3/base_zynq_design_axi_usb2_device_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_4/base_zynq_design_axi_usb2_device_0_4.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_4/base_zynq_design_axi_usb2_device_0_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_4/base_zynq_design_axi_usb2_device_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_5/base_zynq_design_axi_usb2_device_0_5.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_5/base_zynq_design_axi_usb2_device_0_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_5/base_zynq_design_axi_usb2_device_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/ip/base_zynq_design_auto_pc_1/base_zynq_design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/base_zynq_design_ooc.xdc]
set_property is_locked true [get_files /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/base_zynq_design.bd]

read_vhdl -library xil_defaultlib /home/gus/floorplanning/floorplanning.srcs/sources_1/bd/base_zynq_design/hdl/base_zynq_design_wrapper.vhd
read_xdc /home/gus/floorplanning/floorplanning.srcs/constrs_1/new/floorplanning.xdc
set_property used_in_implementation false [get_files /home/gus/floorplanning/floorplanning.srcs/constrs_1/new/floorplanning.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top base_zynq_design_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef base_zynq_design_wrapper.dcp
catch { report_utilization -file base_zynq_design_wrapper_utilization_synth.rpt -pb base_zynq_design_wrapper_utilization_synth.pb }
