# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/floorplanning.xdc

# Block Designs: bd/base_zynq_design/base_zynq_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design || ORIG_REF_NAME==base_zynq_design}]

# IP: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_design_axi_gpio_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_blk_mem_gen_0_0/base_zynq_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_blk_mem_gen_0_0 || ORIG_REF_NAME==base_zynq_design_blk_mem_gen_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_bram_ctrl_0_0/base_zynq_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==base_zynq_design_axi_bram_ctrl_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_axi_periph_0/base_zynq_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_axi_periph_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_xbar_0 || ORIG_REF_NAME==base_zynq_design_xbar_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_0/base_zynq_design_axi_usb2_device_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_0 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_1/base_zynq_design_axi_usb2_device_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_1 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_1}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_2/base_zynq_design_axi_usb2_device_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_2 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_2}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_3/base_zynq_design_axi_usb2_device_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_3 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_3}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_4/base_zynq_design_axi_usb2_device_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_4 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_4}]

# IP: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_5/base_zynq_design_axi_usb2_device_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_5 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_5}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_pc_0 || ORIG_REF_NAME==base_zynq_design_auto_pc_0}]

# IP: bd/base_zynq_design/ip/base_zynq_design_auto_pc_1/base_zynq_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_auto_pc_1 || ORIG_REF_NAME==base_zynq_design_auto_pc_1}]

# XDC: bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_processing_system7_0_0 || ORIG_REF_NAME==base_zynq_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_gpio_0_0/base_zynq_design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_gpio_0_0 || ORIG_REF_NAME==base_zynq_design_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_blk_mem_gen_0_0/base_zynq_design_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_bram_ctrl_0_0/base_zynq_design_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0}]

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==base_zynq_design_rst_processing_system7_0_50M_0}]

# XDC: bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_xbar_0/base_zynq_design_xbar_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_0/base_zynq_design_axi_usb2_device_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_0 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_0/base_zynq_design_axi_usb2_device_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_0 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_0}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_0/base_zynq_design_axi_usb2_device_0_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_1/base_zynq_design_axi_usb2_device_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_1 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_1}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_1/base_zynq_design_axi_usb2_device_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_1 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_1}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_1/base_zynq_design_axi_usb2_device_0_1_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_2/base_zynq_design_axi_usb2_device_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_2 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_2}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_2/base_zynq_design_axi_usb2_device_0_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_2 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_2}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_2/base_zynq_design_axi_usb2_device_0_2_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_3/base_zynq_design_axi_usb2_device_0_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_3 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_3}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_3/base_zynq_design_axi_usb2_device_0_3_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_3 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_3}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_3/base_zynq_design_axi_usb2_device_0_3_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_4/base_zynq_design_axi_usb2_device_0_4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_4 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_4}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_4/base_zynq_design_axi_usb2_device_0_4_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_4 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_4}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_4/base_zynq_design_axi_usb2_device_0_4_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_5/base_zynq_design_axi_usb2_device_0_5.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_5 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_5}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_5/base_zynq_design_axi_usb2_device_0_5_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_zynq_design_axi_usb2_device_0_5 || ORIG_REF_NAME==base_zynq_design_axi_usb2_device_0_5}] {/U0 }]/U0 ]]

# XDC: bd/base_zynq_design/ip/base_zynq_design_axi_usb2_device_0_5/base_zynq_design_axi_usb2_device_0_5_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_pc_0/base_zynq_design_auto_pc_0_ooc.xdc

# XDC: bd/base_zynq_design/ip/base_zynq_design_auto_pc_1/base_zynq_design_auto_pc_1_ooc.xdc

# XDC: bd/base_zynq_design/base_zynq_design_ooc.xdc
